### Get all customers in XML format
GET http://localhost:8000/customers
Content-Type: application/xml

### Get all customers in JSON format
GET http://localhost:8000/customers
Content-Type: application/json

### Get all customers in JSON format
GET http://localhost:8000/customers/20001

### Create a new customer
POST http://localhost:8000/customers

### Get current time
GET http://localhost:8000/api/time?tz=America/New_York,Asia/Kolkata